### ISSUE TITLE
switchTo() method is not found in 2.19

### ISSUE THREAD

**Issue by crocodilechris** [codeborne/selenide#197]
Hi,

I am using the switchTo() method  and after upgrading from 2.16 to 2.19 I get:
```
Stack trace:
   java.lang.NoSuchMethodError: com.codeborne.selenide.Selenide.switchTo
()Lorg/openqa/selenium/WebDriver$TargetLocator;
```
I am calling it that way:
```
switchTo().activeElement();
```
When reverting back to 2.16 it is working again.

**Comment by asolntsev** [comment]
Did you recompile your tests after upgrading to Selenide 2.19?

Sent from my HTC

----- Reply message -----

**Comment by crocodilechris** [comment]
Yes, eclipse did that. I also run a maven `mvn clean install` and `maven package` to ensure it's recompiled.

**Comment by asolntsev** [comment]
I cannot reproduce the problem. Can you provide a full test source and Pim.xml?

Sent from my HTC

----- Reply message -----

**Comment by asolntsev** [comment]
@crocodilechris No, I believe you haven't recompiled tests. Your error `NoSuchMethodError` means exactly that. In Selenide 2.16, method `Selenide.switchTo()` returned `TargetLocator`, and your test is compiled with this version. But in Selenide 2.19, method `Selenide.switchTo()` returns `SelenideTargetLocator` - that's why you are getting `NoSuchMethodError`. Just recompile your tests.

**Comment by crocodilechris** [comment]
Now I investigated deeper and found out what the problem was:
The pom.xml was updated to 2.19, the project was rebuild, but the libs folder was not updated, so the 2.16 package remained and was included in my uber jar.
I now added a clean task to delete all libs explicitly before download or updating them.
I guess the project was compiled with the new version of the framework, but packaged with the remaining old version.
That is the why I got missing ``TargetLocator`` instead of missing ``SelenideTargetLocator``. Compiled as 2.19, but referenced as 2.16...
