### ISSUE TITLE
Configuration.fileDownload = FileDownloadMode.PROXY does not work.

### ISSUE THREAD

**Issue by anyone-can-test** [codeborne/selenide#423]
If Configuration.fileDownload = FileDownloadMode.PROXY is set, then I got a error in the first page.
The error screenshot has "There is no Internet connection.".
In my local PROXY mode is ok, but in remote (selenium node) PROXY mode does not work.
It seems that a selenium node (server) does not permit proxy.

selenide ver. : 4.0

Is there something that I can do to solve it?

My test environment is 
- test machine (gradle test ...) -> selenium hub -> selenium node (chrome driver)

For proxy to work, is there any firewall conditions?
For example, which port should be open?

**Comment by asolntsev** [comment]
@anyone-can-test Hi!
Selenide runs its own "embedded" proxy server on the same machine where tests run.
Probably your grid node just cannot connect to this machine. 
In this case `FileDownloadMode.PROXY` just cannot work, unfortunately. At least I don't know how to implement it.

Selenide proxy runs on random port, so I guess opening a firewall would not help also.

My recommendation is to avoid using Selenium Grid. It may sound rebellious, but it's exactly what I mean. You probably don't need the Grid anymore. Just run tests and browser on the same machine. It's simple, fast and stable.

**Comment by asolntsev** [comment]
@anyone-can-test Hi! 
Any feedback on this topic?
Does it help if we make it possible to configure the port for the selenide proxy server? In this case you could configure your firewall.

**Comment by anyone-can-test** [comment]
@asolntsev 

Because of the proxy firewall issue, I have decided not to download files in test code. I want to download files and verify them, but there is no way as you pointed in using selenium node.
If I can configure selenide proxy port,  that would be helpful. At least I can try.

one more thing
Avoiding selenium grid... then how can I run selenium/selenide tests in parallel, for short execution time?

**Comment by asolntsev** [comment]
It's actually simple. Look how Selenide runs its tests in parallel: 

```
test {
  maxParallelForks = 2
}
```

see https://github.com/codeborne/selenide/blob/master/build.gradle

Or what build system do you use?

**Comment by hyunil-shin** [comment]
@asolntsev 

Recently, I want to test file download again. I am trying using proxy mode.

In Selenium Grid, to use proxy (Configuration.fileDownload = FileDownloadMode.PROXY) which network should be available?
There are a test machine, selenium hub, and selenium nodes.
Is the proxy server started in the test machine?

**Comment by asolntsev** [comment]
@hyunil-shin Yes, proxy server is started on the test machine. You need to setup network so that test machine is accessible from grid node.

**Comment by anyone-can-test** [comment]
@asolntsev 

Could you give me some hints?
I tested two things.
Two cases used the same bmp port (I customized Selenide source to have the port fixed).
- PASS: standalone bmp in test machine (linux) + web browser with proxy setting in my pc (windows)
- FAIL: selenide in test machine (linux) + web browser with proxy setting in my pc (windows)
  - while test executing, I open a site in the web browser.

The web browser said.
```
The connection was reset
The connection to the server was reset while the page was loading.

   The site could be temporarily unavailable or too busy. Try again in a few moments.
   If you are unable to load any pages, check your computer's network connection.
   If your computer or network is protected by a firewall or proxy, make s
```

I am digging it. It is difficult to find out what I missed.

**Comment by anyone-can-test** [comment]
@asolntsev 
It worked in Selenide 4.3.
It would be very helpful. 
- can set a proxy port.
- can set a proxy IP. In Chrome capabilities, hostname (not IP) is provided. Selenium grids do not know the hostname (I modified /etc/hosts, so it works.).


Until now, I found out some problem in the latest Selenide source.
In the latest Selenide source, there might be dependency conflict. 
I got a error message in the log. Guava library version might be something wrong.
Guava 20 removed getHostsText() (https://github.com/google/guava/wiki/Release20) .
```
NoSuchMethodError java.lang.nosuchmethoderror: com.google.common.net.hostandport.gethosttext()ljava/lang/string
```

**Comment by anyone-can-test** [comment]
If I can set a proxy port, there is a issue.
In parallel execution, more than one proxy servers should be started with different ports.

**Comment by asolntsev** [comment]
@anyone-can-test Please upgrade to Selenide 4.8 - all conflicts should be resolved there.

You are right, there is a problem with proxy port if you run tests in parallel in the same JVM.
That's why I recommend to run parallel tests in different processes. 
I usually do it with Gradle `forkEvery` parameter.

**Comment by AgeshAalam** [comment]
Hi
![download_error](https://user-images.githubusercontent.com/44727659/71506161-ca7b1400-28a5-11ea-9e88-2403aa3b7368.PNG)

With proxy enabled, I am able to download a file but it is in the downloads folder not in the reports folder. Once its downloads it is throwing an error that I have attached.

**Comment by asolntsev** [comment]
@AgeshAalam It may happen because Selenide didn't find a proper http header in server response. 
Please read all Selenide logs at the moment of downloading. It should list all http responses with all their headers.

**Comment by AgeshAalam** [comment]
Thank you @asolntsev. I am using Eclipse IDE I could not find any http response log in the console output. Is there any other mechanism to check the selenide response log.

**Comment by asolntsev** [comment]
@AgeshAalam You don't need any special IDE or other tool to read Selenide logs. Just look into the console output when running tests. There should be some lines like this:

```
01:15:06:997 [main] INFO DownloadFileWithProxyServer - Downloaded file: /Users/andrei/projects/selenide/build/reports/tests/8681a8b9-53a2-4ffa-803a-d6b14e26de3d/hello_world.txt
01:15:17:042 [main] INFO DownloadFileWithProxyServer - Just in case, all intercepted responses: Intercepted 1 responses.
  https://127.0.0.1:44692/files/hello_world.txt -> 200 "OK" {content-disposition=attachment; filename=hello_world.txt, Server=Jetty(9.4.21.v20190926), Content-Length=14, Date=Thu, 02 Jan 2020 23:15:06 GMT, Content-Type=text/html} text/html  (14 bytes)
```
